import createMiddleware from "next-intl/middleware";
import { routing } from "./i18n/routing";

export default createMiddleware(routing);

export const config = {
  // Match all pathnames except for:
  // - /api, /_next, /_vercel (Next internals)
  // - Files with a dot (assets like .ico, .png, .svg, .mp4, .xml)
  // - Metadata routes generated by Next.js conventions
  matcher: [
    "/((?!api|_next|_vercel|icon|apple-icon|opengraph-image|sitemap\\.xml|robots\\.txt|.*\\..*).*)",
  ],
};
